// Login
export const LOGIN_FETCHING = "LOGIN_FETCHING";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";

// Register 
export const REGISTER_FETCHING = "REGISTER_FETCHING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

//Transaction
export const TRANSACTION_FETCHING = "TRANSACTION_FETCHING";
export const TRANSACTION_SUCCESS = "TRANSACTION_SUCCESS";
export const TRANSACTION_FAILED = "TRANSACTION_FAILED";
export const TRANSACTION_CLEAR = "TRANSACTION_CLEAR";

//User
export const USER_FETCHING = "USER_FETCHING";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_FAILED = "USER_FAILED";
export const USER_CLEAR = "USER_CLEAR";

//Request
export const REQUEST_FETCHING = "REQUEST_FETCHING";
export const REQUEST_SUCCESS = "REQUEST_SUCCESS";
export const REQUEST_FAILED = "REQUEST_FAILED";
export const REQUEST_CLEAR = "REQUEST_CLEAR";

export const REQUEST_SENDER_FETCHING = "REQUEST_SENDER_FETCHING";
export const REQUEST_SENDER_SUCCESS = "REQUEST_SENDER_SUCCESS";
export const REQUEST_SENDER_FAILED = "REQUEST_SENDER_FAILED";
export const REQUEST_SENDER_CLEAR = "REQUEST_SENDER_CLEAR";


export const REQUEST_RECEIVER_FETCHING = "REQUEST_RECEIVER_FETCHING";
export const REQUEST_RECEIVER_SUCCESS = "REQUEST_RECEIVER_SUCCESS";
export const REQUEST_RECEIVER_FAILED = "REQUEST_RECEIVER_FAILED";
export const REQUEST_RECEIVER_CLEAR = "REQUEST_RECEIVER_CLEAR";

export const REQUEST_EDIT_FETCHING = "REQUEST_EDIT_FETCHING";
export const REQUEST_EDIT_SUCCESS = "REQUEST_EDIT_SUCCESS";
export const REQUEST_EDIT_FAILED = "REQUEST_EDIT_FAILED";




